### ISSUE TITLE
*.mo with no content

### ISSUE THREAD

**Issue by almai** [MicheleBertoli/grunt-po2mo#4]
Compiling the *.po with po2mo results in a *.mo with 0 Byte. When compiling it with Poedit everything works well.

My gruntfile: https://gist.github.com/almai/9951558

**Comment by MicheleBertoli** [comment]
Pushed 072d0d2870778849bfc1628b946cbd05b80d9007, it fixes the "blank file problem" on Windows or, at least, shows an helpful error.
Let me know :)

**Comment by korobochkin** [comment]
I see `>> /bin/sh: msgfmt: command not found`. Blank mo file again. Why?

**Comment by shivapoudel** [comment]
@korobochkin you could try out http://npmjs.org/package/grunt-potomo

**Comment by korobochkin** [comment]
@shivapoudel this stuff require GNU Gettext. I trying to install it but something isn't working.

**Comment by MicheleBertoli** [comment]
@korobochkin as the message says, `msgfmt` is not installed on your computer.

You have to install `gettext` to compile `po`s files:
- Windows: http://gnuwin32.sourceforge.net/packages/gettext.htm
- Mac: `brew install gettext`

@shivapoudel nice way to promote your package but without `msgfmt` he'll have the same problem.

**Comment by MicheleBertoli** [comment]
Updated the readme with the installation instructions: https://github.com/MicheleBertoli/grunt-po2mo/commit/45a845a4689874253bccecb04338ea36df50f81d#diff-04c6e90faac2675aa89e2176d2eec7d8
